// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourApi.Data;

#nullable disable

namespace YourApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourApi.Data.AppMeta", b =>
            {
                b.Property<string>("Key")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("key");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("value");

                b.HasKey("Key");

                b.ToTable("app_meta", (string)null);
            });

            modelBuilder.Entity("YourApi.Data.Health", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CheckedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("checked_at");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("status");

                b.HasKey("Id");

                b.ToTable("health", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
