namespace Streck.AssetTracker.Models;

/// <summary>
/// A physical location (bench, room, site) where assets live.
/// Persisted to the <c>locations</c> table.
/// </summary>
public class Location
{
    /// <summary>Location id. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.</summary>
    public Guid Id { get; set; }

    /// <summary>Human-readable location name, e.g. <c>Bench 3</c>.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Streck site code, e.g. <c>OMA-A</c>.</summary>
    public string Site { get; set; } = string.Empty;

    /// <summary>Row creation timestamp, UTC.</summary>
    public DateTime CreatedAt { get; set; }
}
