namespace Streck.AssetTracker.Models;

/// <summary>
/// An asset owner (typically a Streck employee).
/// Persisted to the <c>owners</c> table.
/// </summary>
public class Owner
{
    /// <summary>Owner id. Generated by Postgres (<c>gen_random_uuid()</c>).</summary>
    public Guid Id { get; set; }

    /// <summary>Display name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Contact email (unique).</summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>Row creation timestamp, UTC.</summary>
    public DateTime CreatedAt { get; set; }
}
