set shell := ["bash", "-cu"]

build:
    dotnet build YourApi.sln -c Debug --nologo

run:
    dotnet run --project YourApi.csproj

test:
    dotnet test YourApi.sln --nologo

format:
    dotnet format YourApi.sln

format-verify:
    dotnet format YourApi.sln --verify-no-changes

ef-migrate name:
    dotnet ef migrations add {{name}} --project YourApi.csproj

ef-update:
    dotnet ef database update --project YourApi.csproj

ef-script from="" to="":
    dotnet ef migrations script {{from}} {{to}} --project YourApi.csproj

ef-remove:
    dotnet ef migrations remove --project YourApi.csproj

up:
    docker compose up -d --build

down:
    docker compose down -v
